In [4]:
import numpy
my_array = numpy.array([23, 24, 28, 1, 4, 20, 0, 9])
print(my_array)


[23 24 28  1  4 20  0  9]


In [7]:
my_array = numpy.arange(5,10000000)
print(my_array)

[      5       6       7 ... 9999997 9999998 9999999]


In [8]:
import numpy as np
print(np.__version__)


2.3.4


In [10]:
import numpy as np
my_arr  =  np.array([1, 2, 3, 4, 5])
print(my_arr)
print(type(my_arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
import numpy as np
my_arr  =  np.array((1, 2, 3, 4, 5))
print(my_arr)
print(type(my_arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [13]:
import numpy as np
my_arr = np.array(42)
print(my_arr)
print(type(my_arr))

42
<class 'numpy.ndarray'>


# 2d array

In [17]:
import numpy as np
my_arr = np.array([[2, 3, 4], [5, 6, 7]])
print(my_arr)

[[2 3 4]
 [5 6 7]]


In [ ]:
# 3d array

In [1]:
import numpy as np
my_array = np.array([[[2, 45, 6, 4],[12, 34, 54, 45],[34, 54, 56,34]]])
print(my_array)

[[[ 2 45  6  4]
  [12 34 54 45]
  [34 54 56 34]]]


In [5]:
import numpy as np
my_array4 = np.array([[[[23, 34, 45, 45],[23,4,54, 34],[34,54,55, 65],[34,2,4,56]]]])
print(my_array4)

[[[[23 34 45 45]
   [23  4 54 34]
   [34 54 55 65]
   [34  2  4 56]]]]


In [ ]:
# 1d, 2d, 3d, arrays

In [7]:
import numpy as np
my_arr = np.array(42)
my_arr1 = np.array([32,43,53,34])
my_array2 = np.array([[2, 3, 4], [5, 6, 7]])
my_array3 = np.array([[[2, 45, 6, 4],[12, 34, 54, 45],[34, 54, 56,34]]])
my_array4 = np.array([[[[23, 34, 45, 45],[23,4,54, 34],[34,54,55, 65],[34,2,4,56]]]])

print(my_arr.ndim)
print(my_arr1.ndim)
print(my_array2.ndim)
print(my_array3.ndim)
print(my_array4.ndim)

0
1
2
3
4


In [24]:
import numpy as np
my_arr = np.array([23,34,38,24,7],ndmin=6)
print(my_arr)
print(my_arr.ndim)

[[[[[[23 34 38 24  7]]]]]]
6


In [ ]:
# indexing the array element

In [25]:
import numpy as np
arr = np.array([23, 4, 45, 29])
print(arr[0])

23


In [26]:
import numpy as np
arr = np.array([23, 4, 45, 29])
print(arr[3])

29


In [27]:
import numpy as np
arr = np.array([23, 4, 45, 29, 243, 34, 59, 39])
print(arr[3]+ arr[5])

63


In [34]:
import numpy as np
arr = np.array([23, 4, 45, 29, 243, 34, 59, 39])
print(arr[3] / arr[5])

0.8529411764705882


In [42]:
import numpy as np
arr = np.array([[23, 43, 1, 4],[2, 34, 99, 25]])
print(arr[1,0])
print(arr.ndim)

2
2


In [52]:
import numpy as np
my_arr = np.array([[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]])
print(my_arr[0, 1, 2])
print(my_array.ndim)

7
3


In [58]:
import numpy as np
my_arr = np.array([[[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12],[13, 14, 15, 16]]]])
print(my_arr[0, 0, 2, 3])

12


In [59]:
import numpy as np
my_arr = np.array([[[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12],[13, 14, 15, 16]]]])
print(my_arr[0, 0, -1, 0])

13


In [ ]:
# slicing the array element

In [63]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:-1])


[2 3 4]


In [74]:
import numpy as np
my_arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print(my_arr[0:2,1])

[2 6]
