In [2]:
import numpy as np
arr = np.array([1, 2, 3, 7])
print(arr.dtype)

int64


In [3]:
import numpy as np
arr = np.array(["apple" ,"bannana"])
print(arr.dtype)

<U7


In [6]:
import numpy as np
arr = np.array(["apple" ,"bannana"], dtype="S")
print(arr)
print(arr.dtype)

[b'apple' b'bannana']
|S7


In [7]:
import numpy as np
arr = np.array([1, 2, 3, 7], dtype="i")
print(arr.dtype)

int32


In [12]:
import numpy as np
arr = np.array([1.0, 2.3, 3.4, 7.5],dtype="S")
print(arr.dtype)
print(arr)

|S3
[b'1.0' b'2.3' b'3.4' b'7.5']


In [14]:
import numpy as np
arr = np.array([1.0, 2.3, 3.4, 7.5],dtype="U")
print(arr.dtype)
print(arr)

<U3
['1.0' '2.3' '3.4' '7.5']


In [2]:
import numpy as np
arr = np.array([1, 2, 3, 7], dtype="i4")
print(arr.dtype)

int32


In [8]:
import numpy as np
arr = np.array(["apple" ,"bannana"], dtype="S7")
print(arr)
print(arr.dtype)

[b'apple' b'bannana']
|S7


In [18]:
import numpy as np
arr = np.array([1.0, 2.0, 3.0, 4.0])
newarray = arr.astype('i')
print(newarray.dtype)
print(arr)

int32
[1. 2. 3. 4.]


In [20]:
import numpy as np
arr = np.array([1.0, 2.0, 3.0, 4.0])
newarray = arr.astype(bool)
print(newarray.dtype)
print(newarray)

bool
[ True  True  True  True]


In [ ]:
# copy and view

In [23]:
import numpy as np
arr = np.array([1, 23, 4, 26, 12])
x = arr.copy()
arr[0] = 10
print(arr)
print(x)

[10 23  4 26 12]
[ 1 23  4 26 12]


In [25]:
import numpy as np
arr = np.array([1, 23, 4, 26, 12])
x = arr.view()
# arr[0] = 10
print(x)
print(arr)

[ 1 23  4 26 12]
[ 1 23  4 26 12]


In [ ]:
# shape of the array

In [2]:
import numpy as np
arr = np.array([[2,4,5,6],[9,43,34,5]])
print(arr.shape)

(2, 4)


In [3]:
import numpy as np
arr = np.array([[[2,4,5,6],[9,43,34,5],[23,34,29,13]]])
print(arr.shape)

(1, 3, 4)


In [5]:
import numpy as np
arr = np.array([2,4,5,6],ndmin=6)
print(arr.shape)

(1, 1, 1, 1, 1, 4)


In [6]:
import numpy as np
my_array4 = np.array([[[[23, 34, 45, 45],[23,4,54, 34],[34,54,55, 65],[34,2,4,56]]]])
print(my_array4.shape)

(1, 1, 4, 4)


In [ ]:
# reshape the array

In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
new_arr = arr.reshape(3, 4)

print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
new_arr = arr.reshape( 1,3, 4)

print(new_arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [21]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
new_arr = arr.reshape(1,1, 1,3, 4)

print(new_arr)

[[[[[ 1  2  3  4]
    [ 5  6  7  8]
    [ 9 10 11 12]]]]]


In [30]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
new_arr = arr.reshape(3, 2, -1)

print(new_arr)


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [35]:
import numpy as np
arr = np.array([[1, 2, 3, 4],[ 7, 8, 9, 10]])
new_arr = arr.reshape(-1)

print(new_arr)

[ 1  2  3  4  7  8  9 10]


In [ ]:
# iterating array 

In [40]:
import numpy as np
arr = np.array([12,34,43,52])
for x in arr:
    print(arr)


[12 34 43 52]
[12 34 43 52]
[12 34 43 52]
[12 34 43 52]


In [47]:
import numpy as np
arr = np.array([[12,34,43,52],[28, 22,20,21]])
for x in arr:
    print(x)

[12 34 43 52]
[28 22 20 21]


In [49]:
import numpy as np
arr = np.array([[12,34,43,52],[28, 22,20,21]])
for x in arr:
    for y in x:
        print(y)

12
34
43
52
28
22
20
21


In [50]:
import numpy as np
arr = np.array([[[12,34,43,52],[28, 22,20,21],[23,34,45,45]]])
for x in arr:
    print(x)

[[12 34 43 52]
 [28 22 20 21]
 [23 34 45 45]]


In [53]:
import numpy as np
arr = np.array([[[12,34,43,52],[28, 22,20,21],[23,34,45,45]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

12
34
43
52
28
22
20
21
23
34
45
45


In [55]:
import numpy as np
arr = np.array([[[12,34,43,52],[28, 22,20,21],[23,34,45,45]]])
for x in np.nditer(arr):
    print(x)

12
34
43
52
28
22
20
21
23
34
45
45


In [56]:
import numpy as np
arr = np.array([[12,34,43,52],[28, 22,20,21]])
for x in np.nditer(arr):
    print(x)

12
34
43
52
28
22
20
21


In [ ]:
# joining array

In [3]:
import numpy as np
arr1 = [1, 2, 3, 4]
arr2 = [5, 6, 7, 8]
new_arr = np.concatenate((arr1, arr2))
print(new_arr)

[1 2 3 4 5 6 7 8]


In [4]:
import numpy as np
arr1 = [1, 2, 3, 4]
arr2 = [5, 6, 7, 8]
arr3 = [9, 10, 11, 12]
new_arr = np.concatenate(((arr1, arr2, arr3)))
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [8]:
import numpy as np
arr1 = [1, 2],[ 3, 4]
arr2 = [5, 6],[ 7, 8]
new_arr = np.concatenate((arr1, arr2),axis=1)
print(new_arr)

[[1 2 5 6]
 [3 4 7 8]]


In [13]:
import numpy as np
arr1 = [1, 2],[ 3, 4]
arr2 = [5, 6],[ 7, 8]
arr3 = [9, 10],[ 11, 12]
new_arr = np.concatenate(((arr1, arr2, arr3)) ,axis=1)
print(new_arr)

[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]


In [16]:
import numpy as np
arr = np.array([1, 2, 3, 4])
arr1 = np.array([5, 6, 7, 8])
new_arr = np.stack((arr, arr1), axis=1)
print(new_arr)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [19]:
import numpy as np
arr = np.array([1, 2, 3, 4])
arr1 = np.array([5, 6, 7, 8])
arr2 = np.array([9, 10, 11, 12])
new_arr = np.stack(((arr, arr1,arr2)), axis=1)
print(new_arr)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [21]:
import numpy as np
arr = np.array([1, 2, 3, 4])
arr1 = np.array([5, 6, 7, 8])
new_arr = np.hstack((arr, arr1))
print(new_arr)

[1 2 3 4 5 6 7 8]


In [22]:
import numpy as np
arr = np.array([1, 2, 3, 4])
arr1 = np.array([5, 6, 7, 8])
new_arr = np.vstack((arr, arr1))
print(new_arr)

[[1 2 3 4]
 [5 6 7 8]]


In [23]:
import numpy as np
arr = np.array([1, 2, 3, 4])
arr1 = np.array([5, 6, 7, 8])
new_arr = np.dstack((arr, arr1))
print(new_arr)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [32]:
import numpy as np
arr = np.array([23,43, 22, 40, 59])
new_arr = np.array_split(arr,3)
print(new_arr)

[array([23, 43]), array([22, 40]), array([59])]


In [35]:
import numpy as np
arr = np.array([23,43, 22, 40, 59])
new_arr = np.array_split(arr,3)
print(new_arr[0])
print(new_arr[1])
print(new_arr[2])

[23 43]
[22 40]
[59]


In [52]:
import numpy as np
arr = np.array([[1, 2, 3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[18,19,20]])
new_arr = np.array_split(arr, 3)
print(new_arr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [18, 19, 20]])]


In [56]:
import numpy as np
arr = np.array([[1, 2, 3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[18,19,20]])
new_arr = np.array_split(arr, 3, axis=1)
print(new_arr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [18]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [19]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [20]])]


In [57]:
import numpy as np
arr = np.array([[1, 2, 3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[18,19,20]])
new_arr = np.hsplit(arr, 3)
print(new_arr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [18]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [19]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [20]])]


In [ ]:
# array search

In [62]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 4, 4])
new_arr = np.where(arr == 4)
print(new_arr)

(array([3, 6, 7]),)


In [67]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 4, 4])
new_arr = np.where(arr % 3)
print(new_arr)

(array([0, 1, 3, 4, 6, 7]),)


In [68]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 4, 4])
new_arr = np.where(arr % 3==1)
print(new_arr)

(array([0, 3, 6, 7]),)


In [77]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 4, 4])
new_arr = np.searchsorted(arr, 5)
print(new_arr)

4


In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 4, 4])
new_arr = np.searchsorted(arr, 2,side='left')
print(new_arr)

1


In [ ]:
# sorted array

In [3]:
import numpy as np
arr = np.array(['bannana','apple','grapes'])
print(np.sort(arr))

['apple' 'bannana' 'grapes']


In [4]:
import numpy as np
arr = np.array([1, 21, 12, 100, 22, 19])
print(np.sort(arr))

[  1  12  19  21  22 100]


In [6]:
import numpy as np
arr = np.array([[1, 21, 12],[ 100, 22, 19]])
print(np.sort(arr))

[[  1  12  21]
 [ 19  22 100]]


In [10]:
import numpy as np
arr = np. array([23,43, 21,12,34])
x = [True,False,True,True,True]
newarr = arr[x]
print(newarr)

[23 21 12 34]
