In [ ]:
# LCM

In [1]:
import numpy as np

num1 = 3
num2 = 4

x = np.lcm(num1, num2)

print(x)

12


In [6]:
import numpy as np

x = np.array([2, 3, 4])

x1 = np.lcm.reduce(x)

print(x1)



12


In [7]:
import numpy as np

x = np.array([1, 11])

x1 = np.lcm.reduce(x)

print(x1)

11


In [ ]:
# GCM

In [9]:
import numpy as np

num1 = 2
num2 = 3

x = np.gcd(num1, num2)

print(x)

1


In [15]:
import numpy as np

num = np.array([11, 40, 5])

x = np.gcd.reduce(num)

print(x)


1


In [16]:
import numpy as np

num = np.array([11, 40, 5, 39, 28, 10])

x = np.gcd.reduce(num)

print(x)


1


In [ ]:
# Trigonmatic

In [17]:
import numpy as np

num = np.sin(np.pi/2)

print(num)

1.0


In [4]:
import numpy as np

num = np.sin(np.deg2rad(90))

print(num)

1.0


In [2]:
import numpy as np

x = np.array([90, 180, 280, 360])

num = np.rad2deg(x)

print(num)

[ 5156.62015618 10313.24031235 16042.81826366 20626.48062471]


In [5]:
import numpy as np

num = np.cos(np.pi/2)

print(num)

6.123233995736766e-17


In [6]:
import numpy as np

num = np.cos(np.deg2rad(90))

print(num)

6.123233995736766e-17


In [7]:
import numpy as np

num = np.tan(np.deg2rad(90))

print(num)

1.633123935319537e+16


In [8]:
import numpy as np

num = np.tan(np.pi/2)

print(num)

1.633123935319537e+16


In [9]:
import numpy as np

x = np.arcsin(1)

print(x)

1.5707963267948966


In [10]:
import numpy as np

x = np.array([-1, 1, 0.1])

num = np.arcsin(x)

print(num)

[-1.57079633  1.57079633  0.10016742]


In [ ]:
# hypothesis

In [11]:
import numpy as np

x = 2
y = 5

num = np.hypot(x, y)

print(num)

5.385164807134504


In [ ]:
# set

In [2]:
import numpy as np

a = np.array([1, 2, 1,2 ,4, 6, 9, 9, 10, 11])

x = np.unique(a)

print(x)

[ 1  2  4  6  9 10 11]


In [ ]:
# FINDING UNION

In [5]:
import numpy as np

num1 = np.array([1, 2, 3, 4])
num2 = np.array([5, 6, 7, 8])

x = np.union1d(num1, num2)

print(x)

[1 2 3 4 5 6 7 8]


In [6]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

[3 4]
