In [ ]:
# Generate random number using radient() method

In [8]:
from numpy import random
x = random.randint(100)
print(x)

74


In [17]:
from numpy import random
x = random.randint(100, 200)
print(x)

130


In [ ]:
# generate random float number by using rand() method

In [24]:
from numpy import random
x = random.rand(100)
print (x)

[[0.97077865 0.4684457  0.94307064 ... 0.58618431 0.00708614 0.02842094]
 [0.48102096 0.89065515 0.47456066 ... 0.87731082 0.14205356 0.38767603]
 [0.8023423  0.77051542 0.55491436 ... 0.38372551 0.2882579  0.95986012]
 ...
 [0.89304714 0.18835178 0.45893918 ... 0.43463101 0.47456242 0.07486349]
 [0.4742633  0.4070947  0.52167704 ... 0.05742712 0.77433557 0.09014951]
 [0.57731284 0.29289467 0.49696279 ... 0.10789222 0.5737105  0.47627559]]


In [28]:
from numpy import random
x = random.rand()
print (x)

0.5093095662736756


In [ ]:
# Generate random array 

In [5]:
from numpy import random
x = random.randint(100, size = 6)

print(x)

[41 65 28 71 38  5]


In [7]:
from numpy import random
x = random.randint(100,110, size = 6)

print(x)

[106 102 104 108 108 109]


In [10]:
from numpy import random
x = random.randint(100, size = (2, 2))

print(x)

[[54 76]
 [22 64]]


In [16]:
from numpy import random
x = random.randint(100,110, size = (2, 3))

print(x)

[[105 109 106]
 [105 100 107]]


In [22]:
from numpy import random
x = random.rand(10)

print(x)

[0.67970381 0.62170924 0.08647624 0.02745423 0.42633132 0.73439517
 0.3932127  0.1860431  0.45271965 0.75111879]


In [25]:
from numpy import random
x = random.rand(2,3)

print(x)

[[0.258895   0.58684263 0.21343731]
 [0.22305127 0.34209247 0.34581248]]


In [ ]:
# GEnerate numbers from array using choice() method

In [29]:
from numpy import random
x = random.choice([23, 21, 37, 19, 1])

print(x)

1


In [35]:
from numpy import random
x = random.choice([23, 21, 37, 19, 1], size = (2,3))

print(x)

[[37 23 19]
 [21 19 19]]


In [ ]:
# Data distribution

In [55]:
from numpy import random
x = random.choice([21, 2, 18, 19, 100], p = [0.5, 0.0, 0.2, 0.3, 0], size = 15)

print(x)

[21 19 21 21 19 18 19 19 21 19 18 19 21 21 19]


In [56]:
from numpy import random
x = random.choice([21, 2, 18, 19, 100], p = [0.5, 0.0, 0.2, 0.3, 0])

print(x)

21


In [57]:
from numpy import random
x = random.choice([21, 2, 18, 19, 100], p = [0.5, 0.0, 0.2, 0.3, 0], size = (2, 3))

print(x)

[[18 21 21]
 [21 18 19]]


In [ ]:
# Random permutations

In [ ]:
# shuffle() method

In [58]:
import numpy as np
x = np.array([12, 13, 14, 15, 16, 17])

random.shuffle(x)

print(x)

[15 13 14 12 17 16]


In [ ]:
# permutation() method

In [59]:
from numpy import random
import numpy as np

x = np.array([1, 2, 3, 4, 5])

new_arr = random.permutation(X)

print(new_arr)

[12 13 14 15 16 17]
