In [ ]:
 # Truncation and fix()

In [2]:
import numpy as np

x = np.fix([12.2333, 23, 1.2])

print(x)

[12. 23.  1.]


In [3]:
import numpy as np

x = np.fix([12.2333, -2.334, -1.2])

print(x)

[12. -2. -1.]


In [4]:
import numpy as np

x = np.trunc([12.2333, -2.334, -1.2])

print(x)

[12. -2. -1.]


In [10]:
import numpy as np

x = np.fix([12.2333, -2.334, -1.2])
x1 = np.float16([12.2333, -2.334, -1.2])
print(x)
print(x1)

[12. -2. -1.]
[12.234 -2.334 -1.2  ]


In [ ]:
# Rounding()

In [12]:
import numpy as np

x = np.around([12.5333, -2.334, -1.2])

print(x)

[13. -2. -1.]


In [13]:
import numpy as np

x = np.round([12.5333, -2.334, -1.2])

print(x)

[13. -2. -1.]


In [14]:
import numpy as np

x = np.round([12.5333, -2.534, -1.5])

print(x)

[13. -3. -2.]


In [19]:
import numpy as np

x = np.array([12.5333, -2.334, -1.2])

# 2 decimal number
new_value = np.around(x, 2)

# 3 decimal number
arr = np.around(x, 3)

# nearest value
arr1 = np.around(x)

print(new_value)
print(arr)
print(arr1)

[12.53 -2.33 -1.2 ]
[12.533 -2.334 -1.2  ]
[13. -2. -1.]


In [ ]:
# floor()

In [20]:
import numpy as np

x = np.floor([12.5333, -2.334, -1.2])

print(x)

[12. -3. -2.]


In [27]:
import numpy as np

x = np.array([12.5333, -2.334, -1.2])

x1 = np.around(np.add(x,2.5))

arr = np.floor(x)

print(arr)
print(x1)

[12. -3. -2.]
[15.  0.  1.]


In [ ]:
# Ceil()

In [29]:
import numpy as np

x = np.ceil([1.3333, 2.0, 1.5555])

print(x)

[2. 2. 2.]


In [30]:
import numpy as np

x = np.ceil([1.3333, 2.0, -1.5555])

print(x)

[ 2.  2. -1.]


In [31]:
import numpy as np

arr = np.array([2.333, 2.0, 3.5, -2.8])

# truncation
arr1 = np.trunc(arr)

# fix
arr2 = np.fix(arr)

# round
arr3 = np.round(arr)

# floor
arr4 = np.floor(arr)

#ceil
arr5 = np.ceil(arr)

print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)

[ 2.  2.  3. -2.]
[ 2.  2.  3. -2.]
[ 2.  2.  4. -3.]
[ 2.  2.  3. -3.]
[ 3.  2.  4. -2.]


In [ ]:
# log

In [40]:
import numpy as np

arr = np.array([1, 10])

print(np.log2(arr))

[0.         6.64385619]


In [39]:
import numpy as np

arr = np.array([1, 10])

print(np.log10(arr))

[0. 2.]


In [38]:
import numpy as np

arr = np.array([1, 100])

print(np.log(arr))

[0.         4.60517019]


In [52]:
from math import log
import numpy as np

nlog = np.frompyfunc(log, 2, 1)
print(nlog(100, 18))

1.5932795403938245


In [59]:
import numpy as np

x = np.array([100, 105, 120])

returns = np.log(x[1:]/x[:1])

print(returns)

[0.04879016 0.18232156]


In [ ]:
# Summations

In [64]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 9])

print(np.sum([arr1, arr2]))

37


In [68]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 9])

print(np.sum([arr1, arr2], axis = 1))

[10 27]


In [ ]:
# Cummulative summation

In [70]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
# arr2 = np.array([5, 6, 7, 9])

print(np.cumsum([arr1]))

[ 1  3  6 10]


In [71]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 9])

print(np.cumsum([arr1, arr2]))

[ 1  3  6 10 15 21 28 37]


In [73]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 9])
newarr = np.cumsum([arr1, arr2])

print(np.sum(newarr))

121


In [ ]:
# product 

In [4]:
import numpy as np

vec1 = np.array([1, 2, 5, 9])
vec2 = np.array([2, 8, 5, 3])  # clacuclting the multplition of vec1 and vec2

new_vec = np.prod([vec1, vec2])

print("multipling vec_total:", new_vec)

multipling vec_total: 21600


In [6]:
import numpy as np

vec1 = np.array([[1, 2],[ 5, 9]])
vec2 = np.array([[2, 8], [5, 3]])  # clacuclting the multplition of vec1 and vec2 using 2 dimension array

new_vec = np.prod([vec1, vec2])

print(new_vec)

21600


In [12]:
import numpy as np

vec1 = np.array([1, 2, 5, 9])
vec2 = np.array([2, 8, 5, 3])  # clacuclting the multplition of vec1 and vec2

new_vec = np.prod([vec1, vec2], axis=0) # multipling coloums

print(new_vec)

[ 2 16 25 27]


In [ ]:
import numpy as np

vec1 = np.array([1, 2, 5, 9])
vec2 = np.array([2, 8, 5, 3])  # clacuclting the multplition of vec1 and vec2

new_vec = np.prod([vec1, vec2], axis=1) # multpling rows

print(new_vec)

In [ ]:
# cummlate product

In [16]:
import numpy as np

vec1 = np.array([1, 2, 5, 9])
vec2 = np.array([2, 8, 5, 3])  # clacuclting the multplition of vec1 and vec2

new_vec = np.cumprod([vec1, vec2])

print("multipling vec_total:", new_vec)

multipling vec_total: [    1     2    10    90   180  1440  7200 21600]


In [18]:
import numpy as np

vec1 = np.array([[1, 2],[ 5, 9]])
vec2 = np.array([[2, 8], [5, 3]])  # clacuclting the multplition of vec1 and vec2 using 2 dimension array

new_vec = np.cumprod([vec1, vec2])

print(new_vec)

[    1     2    10    90   180  1440  7200 21600]


In [19]:
import numpy as np

vec1 = np.array([1, 2, 5, 9])
vec2 = np.array([2, 8, 5, 3])  # clacuclting the multplition of vec1 and vec2

new_vec = np.cumprod([vec1, vec2], axis=0) # multipling coloums

print(new_vec)

[[ 1  2  5  9]
 [ 2 16 25 27]]


In [20]:
import numpy as np

vec1 = np.array([1, 2, 5, 9])
vec2 = np.array([2, 8, 5, 3])  # clacuclting the multplition of vec1 and vec2

new_vec = np.cumprod([vec1, vec2], axis=1) # multpling rows

print(new_vec)

[[  1   2  10  90]
 [  2  16  80 240]]


In [ ]:
# Difference

In [22]:
import numpy as np

x = np.diff([1, 5, 3, 4])

print(x)

[ 4 -2  1]


In [27]:
import numpy as np

vec1 = np.array([1, 2, 5, 9])
vec2 = np.array([2, 8, 5, 3])  

new_vec = np.diff([vec1, vec2]) 
print(new_vec)

[[ 1  3  4]
 [ 6 -3 -2]]


In [32]:
import numpy as np

x = np.array([1, 5, 3, 4])

new = np.diff(x , n=2) # discert the funtion from first to sprilt 2nd time from the fist output

print(new)

[-6  3]
