In [ ]:
# noraml iteration

In [2]:
x =[20, 30 , 38,20]
y= [30, 27, 39, 10]
z = []
for i, j in zip(x, y):
    z.append(i+j)
print(z)

[50, 57, 77, 30]


In [ ]:
# Ufunc format

In [3]:
import numpy as np
x = [19,10,12,29]
y = [29,38,49,34]

z = np.add(x,y)

print(z)

[48 48 61 63]


In [ ]:
# creating a function

In [20]:
import numpy as np 

def myadd(x, y):
   return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


In [21]:
import numpy as np
print(type(np.add))

<class 'numpy.ufunc'>


In [24]:
import numpy as np
print(type(np.concatenate))

<class 'numpy._ArrayFunctionDispatcher'>


In [27]:
import numpy as np
if type(np.add) == np.ufunc:
    print("it ufunc")
else:
    print("it not a ufunc")

it ufunc


In [ ]:
# Simple arithmetic operation

In [ ]:
# Addition

In [28]:
import numpy as np

myarr1 = [ 12, 38, 40, 28]
myarr2 = [ 23, 28, 20, 30]

newarr = np.add(myarr1, myarr2)

print(newarr)

[35 66 60 58]


In [4]:
import numpy as np
a = np.array([27, 23, 28])
b = np.add(a, 1)
print(a)

[27 23 28]


In [8]:
import numpy as np

A = np.array([[1, 2, 3, 4],
             [5, 6, 7, 8]])
B = np.array([9, 10, 11, 12])

print(np.add(A, B))

[[10 12 14 16]
 [14 16 18 20]]


In [10]:
import numpy as np 
a = np.array([23,33, 43],dtype=np.int8)
b = np.array([2,3, 1],dtype=np.int32)
print(np.add(a, b))

[25 36 44]


In [11]:
import numpy as np 
a = np.array([23,33, 43],dtype=np.int32)
b = np.array([2,3, 1],dtype=np.int32)
print(np.add(a, b))

[25 36 44]


In [ ]:
# Subtraction method

In [12]:
import numpy as np

myarr1 = [ 12, 38, 40, 28]
myarr2 = [ 23, 28, 20, 30]

newarr = np.subtract(myarr1, myarr2)

print(newarr)

[-11  10  20  -2]


In [14]:
import numpy as np 

a = np.array([23,33, 43],dtype=np.int8)
b = np.array([2,3, 1],dtype=np.int32)

print(np.subtract(a, b))

[21 30 42]


In [15]:
import numpy as np 

a = np.array([23,33, 43],dtype=np.int32)
b = np.array([2,3, 1],dtype=np.int32)

print(np.subtract(a, b))

[21 30 42]


In [17]:
import numpy as np

A = np.array([[1, 2, 3, 4],
             [5, 6, 7, 8]])
B = np.array([9, 10, 11, 12])

print(np.subtract(B, A))

[[8 8 8 8]
 [4 4 4 4]]


In [ ]:
# Multiplication method

In [18]:
import numpy as np

myarr1 = [ 12, 38, 40, 28]
myarr2 = [ 23, 28, 20, 30]

newarr = np.multiply(myarr1, myarr2)

print(newarr)

[ 276 1064  800  840]


In [19]:
import numpy as np 

a = np.array([23,33, 43],dtype=np.int8)
b = np.array([2,3, 1],dtype=np.int32)

print(np.multiply(a, b))

[46 99 43]


In [20]:
import numpy as np

A = np.array([[1, 2, 3, 4],
             [5, 6, 7, 8]])
B = np.array([9, 10, 11, 12])

print(np.multiply(B, A))

[[ 9 20 33 48]
 [45 60 77 96]]


In [ ]:
# Divison method

In [21]:
import numpy as np

myarr1 = [ 12, 38, 40, 28]
myarr2 = [ 23, 28, 20, 30]

newarr = np.divide(myarr1, myarr2)

print(newarr)

[0.52173913 1.35714286 2.         0.93333333]


In [22]:
import numpy as np 

a = np.array([23,33, 43],dtype=np.int8)
b = np.array([2,3, 1],dtype=np.int32)

print(np.divide(a, b))

[11.5 11.  43. ]


In [23]:
import numpy as np

A = np.array([[1, 2, 3, 4],
             [5, 6, 7, 8]])
B = np.array([9, 10, 11, 12])

print(np.divide(B, A))

[[9.         5.         3.66666667 3.        ]
 [1.8        1.66666667 1.57142857 1.5       ]]


In [ ]:
# Power method

In [24]:
import numpy as np

myarr1 = [ 12, 38, 40, 28]
myarr2 = [ 23, 28, 20, 30]

newarr = np.power(myarr1, myarr2)

print(newarr)

[-5038753926841630720   333500598735339520  1152921504606846976
  1152921504606846976]


In [25]:
import numpy as np

A = np.array([[1, 2, 3, 4],
             [5, 6, 7, 8]])
B = np.array([9, 10, 11, 12])

print(np.power(B, A))

[[        9       100      1331     20736]
 [    59049   1000000  19487171 429981696]]


In [ ]:
# Remainder method

In [27]:
import numpy as np

myarr1 = [ 12, 38, 40, 28]
myarr2 = [ 23, 28, 20, 30]

newarr = np.remainder(myarr1, myarr2)

print(newarr)

[12 10  0 28]


In [28]:
import numpy as np

A = np.array([[1, 2, 3, 4],
             [5, 6, 7, 8]])
B = np.array([9, 10, 11, 12])

print(np.remainder(B, A))

[[0 0 2 0]
 [4 4 4 4]]


In [29]:
import numpy as np

A = np.array([[1, 2, 3, 4],
             [5, 6, 7, 8]])
B = np.array([9, 10, 11, 12])

print(np.mod(B, A))

[[0 0 2 0]
 [4 4 4 4]]


In [ ]:
# Quotient and mod

In [31]:
import numpy as np

myarr1 = [ 12, 38, 40, 28]
myarr2 = [ 23, 28, 20, 30]

newarr = np.divmod(myarr1, myarr2)

print(newarr)

(array([0, 1, 2, 0]), array([12, 10,  0, 28]))


In [32]:
import numpy as np

A = np.array([[1, 2, 3, 4],
             [5, 6, 7, 8]])
B = np.array([9, 10, 11, 12])

print(np.divmod(B, A))

(array([[9, 5, 3, 3],
       [1, 1, 1, 1]]), array([[0, 0, 2, 0],
       [4, 4, 4, 4]]))


In [ ]:
# Absolute

In [34]:
import numpy as np

myarr1 = [ 12, 38, 40, 28]

newarr = np.absolute(myarr1)

print(newarr)

[12 38 40 28]


In [35]:
import numpy as np

myarr1 = [ 12, -38, -40, 28]

newarr = np.absolute(myarr1)

print(newarr)

[12 38 40 28]
